//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedSys
{
    using System;
    using System.Collections.Generic;
    
    public partial class med
    {
        public Nullable<double> 内部ID { get; set; }
        public string 报告表编码 { get; set; }
        public string 首次_跟踪报告 { get; set; }
        public string 新的 { get; set; }
        public string 报告类型 { get; set; }
        public string 严重不良反应 { get; set; }
        public string 报告单位类别 { get; set; }
        public string 性别 { get; set; }
        public Nullable<System.DateTime> 出生日期 { get; set; }
        public Nullable<double> 年龄 { get; set; }
        public string 年龄单位 { get; set; }
        public string 名族 { get; set; }
        public string 体重 { get; set; }
        public string 原患疾病 { get; set; }
        public string 医院名称 { get; set; }
        public string 既往药品不良反应_事件 { get; set; }
        public string 家族药品不良反应_事件 { get; set; }
        public string 相关重要信息 { get; set; }
        public string 怀疑_并用 { get; set; }
        public Nullable<double> 序号 { get; set; }
        public string 批准文号 { get; set; }
        public string 商品名称 { get; set; }
        public string 通用名称 { get; set; }
        public string 剂型 { get; set; }
        public string 生产厂家 { get; set; }
        public Nullable<double> 生产批号 { get; set; }
        public Nullable<double> 用量 { get; set; }
        public string 用量单位 { get; set; }
        public Nullable<double> 用药_日 { get; set; }
        public Nullable<double> 用药_次 { get; set; }
        public string 给药途径 { get; set; }
        public Nullable<System.DateTime> 用药开始时间 { get; set; }
        public Nullable<System.DateTime> 用药结束时间 { get; set; }
        public string 用药原因 { get; set; }
        public string 不良反应名称 { get; set; }
        public Nullable<System.DateTime> 不良反应_事件发生时间 { get; set; }
        public string 不良反应_事件过程描述 { get; set; }
        public string 不良反应结果 { get; set; }
        public string 后遗症表现 { get; set; }
        public string 死亡时间 { get; set; }
        public string 死亡原因 { get; set; }
        public string 停药减药后反应是否减轻或消失 { get; set; }
        public string 再次使用可疑药是否出现同样反应 { get; set; }
        public string 对原患疾病影响 { get; set; }
        public string 报告人评价 { get; set; }
        public string 报告单位评价 { get; set; }
        public Nullable<System.DateTime> 报告日期 { get; set; }
        public string 报告单位请填写信息来源 { get; set; }
        public string 备注 { get; set; }
        public Nullable<System.DateTime> 国家中心接收时间 { get; set; }
        public string 报告地区名称 { get; set; }
        public string 县评价 { get; set; }
        public string 市评价 { get; set; }
        public string 省评价 { get; set; }
        public string 国家评价 { get; set; }
        public Nullable<System.DateTime> 县评价时间 { get; set; }
        public Nullable<System.DateTime> 市评价时间 { get; set; }
        public string 省评价时间 { get; set; }
        public string 国家评价时间 { get; set; }
        public long ID { get; set; }
    }
}
